const movieRepository = require('../repositories/movie.repository');
const embeddingService = require('../services/embedding.service');
const logger = require('../utils/logger');

const SEED_MOVIES = [
  {
    id: 157336,
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage across deep space and time for human survival.',
    genres: ['Science Fiction', 'Drama', 'Adventure'],
    vote_average: 8.4,
    popularity: 145.2,
    release_date: '2014-11-05',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  },
  {
    id: 27205,
    title: 'Inception',
    overview: 'Cobb, a skilled thief who steals corporate secrets through the use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O. in a mind-bending psychological heist with complex layers of reality.',
    genres: ['Action', 'Science Fiction', 'Adventure'],
    vote_average: 8.4,
    popularity: 120.5,
    release_date: '2010-07-15',
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
  },
  {
    id: 550,
    title: 'Fight Club',
    overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more in an unreliable reality and mind-bending psychological thriller with an unexpected plot twist.',
    genres: ['Drama', 'Thriller'],
    vote_average: 8.4,
    popularity: 98.3,
    release_date: '1999-10-15',
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent against a rising psychopathic criminal mastermind known as the Joker in Gotham City.',
    genres: ['Drama', 'Action', 'Crime', 'Thriller'],
    vote_average: 8.5,
    popularity: 130.0,
    release_date: '2008-07-16',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  },
  {
    id: 238,
    title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone mafia crime family when patriarch Vito Corleone passes control of his clandestine empire to his reluctant youngest son.',
    genres: ['Drama', 'Crime'],
    vote_average: 8.7,
    popularity: 110.4,
    release_date: '1972-03-14',
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  },
  {
    id: 603,
    title: 'The Matrix',
    overview: 'Set in the 22nd century, The Matrix tells the story of a computer hacker who learns from mysterious rebels about the true nature of his reality and his role in the war against artificial intelligence and cyberpunk controllers.',
    genres: ['Action', 'Science Fiction'],
    vote_average: 8.2,
    popularity: 95.0,
    release_date: '1999-03-30',
    poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
  },
  {
    id: 496243,
    title: 'Parasite',
    overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected social inequality class division and dark satire incident.',
    genres: ['Comedy', 'Thriller', 'Drama'],
    vote_average: 8.5,
    popularity: 88.0,
    release_date: '2019-05-30',
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  },
  {
    id: 8587,
    title: 'The Lion King',
    overview: 'A young lion prince named Simba flees his kingdom after the murder of his father, only to learn the true meaning of responsibility, family friendship, and bravery in a heartwarming animated adventure.',
    genres: ['Animation', 'Family', 'Drama'],
    vote_average: 8.3,
    popularity: 80.5,
    release_date: '1994-06-23',
    poster_path: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
  },
  {
    id: 324857,
    title: 'Spider-Man: Into the Spider-Verse',
    overview: 'Teenager Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from alternate multiverse dimensions to stop a threat to all reality in quantum parallel timelines.',
    genres: ['Action', 'Adventure', 'Animation', 'Science Fiction'],
    vote_average: 8.4,
    popularity: 90.2,
    release_date: '2018-12-06',
    poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
  },
  {
    id: 354912,
    title: 'Coco',
    overview: 'Despite his family\'s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician and journeys through the Land of the Dead in a heartwarming animated tale of family and remembrance.',
    genres: ['Family', 'Animation', 'Fantasy', 'Music'],
    vote_average: 8.2,
    popularity: 75.0,
    release_date: '2017-10-27',
    poster_path: '/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
  },
  {
    id: 329865,
    title: 'Arrival',
    overview: 'Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat in deep first contact communication and time paradoxes.',
    genres: ['Drama', 'Science Fiction', 'Mystery'],
    vote_average: 7.9,
    popularity: 65.0,
    release_date: '2016-11-10',
    poster_path: '/x2O0QCw0st2Cr6bCenHOtQyT2r6.jpg',
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    overview: 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison and finds hope, resilience, and lifelong brotherhood.',
    genres: ['Drama', 'Crime'],
    vote_average: 8.7,
    popularity: 125.0,
    release_date: '1994-09-23',
    poster_path: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II and the ensuing moral guilt and political interrogation.',
    genres: ['Drama', 'History'],
    vote_average: 8.1,
    popularity: 115.0,
    release_date: '2023-07-19',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
  },
  {
    id: 244786,
    title: 'Whiplash',
    overview: 'Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost in an obsessive toxic mentorship dynamic.',
    genres: ['Drama', 'Music'],
    vote_average: 8.4,
    popularity: 70.0,
    release_date: '2014-10-10',
    poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
  },
  {
    id: 120,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    overview: 'Young hobbit Frodo Baggins, after inheriting a mysterious ring, must leave his home and journey to the fires of Mount Doom to destroy it in an epic medieval fantasy war.',
    genres: ['Adventure', 'Fantasy', 'Action'],
    vote_average: 8.4,
    popularity: 110.0,
    release_date: '2001-12-18',
    poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cDK6.jpg',
  },
  {
    id: 807,
    title: 'Se7en',
    overview: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives in a dark chilling neo-noir murder mystery investigation.',
    genres: ['Crime', 'Mystery', 'Thriller'],
    vote_average: 8.3,
    popularity: 85.0,
    release_date: '1995-09-22',
    poster_path: '/6yoghtyTpznpBik8EngEmJskVUO.jpg',
  },
  {
    id: 857,
    title: 'Saving Private Ryan',
    overview: 'As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield. A captain and his unit embark on a perilous mission to find the fourth in intense World War II sacrifice.',
    genres: ['Drama', 'History', 'War'],
    vote_average: 8.2,
    popularity: 80.0,
    release_date: '1998-07-24',
    poster_path: '/uqx37cS8cpHg8x35f9U5IBlrCV3.jpg',
  },
  {
    id: 76341,
    title: 'Mad Max: Fury Road',
    overview: 'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken in high-octane vehicular combat against tyrannical warlords.',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    vote_average: 7.6,
    popularity: 78.0,
    release_date: '2015-05-13',
    poster_path: '/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
  },
  {
    id: 37165,
    title: 'The Truman Show',
    overview: 'An insurance salesman discovers his entire life is actually a constructed reality television show broadcast 24/7 to the entire world, living with an unreliable fake reality.',
    genres: ['Comedy', 'Drama'],
    vote_average: 8.1,
    popularity: 72.0,
    release_date: '1998-06-04',
    poster_path: '/vuza0WqY239yBNa1n8Fe9Z19LsW.jpg',
  },
  {
    id: 19404,
    title: 'Dilwale Dulhania Le Jayenge',
    overview: 'Raj and Simran meet on a train through Europe and fall in love, but Simran is already promised to another man in a heartwarming romantic comedy and timeless tale.',
    genres: ['Comedy', 'Drama', 'Romance'],
    vote_average: 8.5,
    popularity: 60.0,
    release_date: '1995-10-20',
    poster_path: '/lfR2qbcrRhGFyZ6x3q8Z3nK1K5V.jpg',
  }
];

async function seedDatabase() {
  logger.info(`🌱 Seeding ${SEED_MOVIES.length} benchmark movies with 1536-dim vector embeddings into database...`);
  for (const movie of SEED_MOVIES) {
    await movieRepository.upsertMovie(movie);
  }
  logger.info(`✅ Seeded ${SEED_MOVIES.length} movies successfully into PostgreSQL Neon & memory store.`);
}

if (require.main === module) {
  seedDatabase().then(() => process.exit(0));
}

module.exports = { seedDatabase, SEED_MOVIES };
